spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
application:
  security:
    jwt:
      secret-key: 9c99904df17a54e487b44d8722424784b13a0e46c6b38723b5afb3b722c2024c
      expiration: 86400000 # one day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:3000/activate-account